insert into public.groups (code, display_order, phase)
values
  ('A', 1, 'groups'),
  ('B', 2, 'groups'),
  ('C', 3, 'groups'),
  ('D', 4, 'groups'),
  ('E', 5, 'groups'),
  ('F', 6, 'groups'),
  ('G', 7, 'groups'),
  ('H', 8, 'groups'),
  ('I', 9, 'groups'),
  ('J', 10, 'groups'),
  ('K', 11, 'groups'),
  ('L', 12, 'groups')
on conflict (code) do update
set display_order = excluded.display_order,
    phase = excluded.phase;

insert into public.participants (
  display_name,
  represented_country,
  cartola_team_name,
  cartola_team_id,
  group_id,
  seed_label,
  is_active
)
values
  ('Alan Junior', 'Africa do Sul', 'ALL BLACKS C.R.F', 50235319, (select id from public.groups where code = 'A'), 'A1', true),
  ('Alex Melo', 'Alemanha', 'AdmGpi-FC', 848616, (select id from public.groups where code = 'E'), 'E1', true),
  ('Angel Emir', 'Arabia Saudita', 'Pangatirumiruaru F.C', 47684449, (select id from public.groups where code = 'H'), 'H1', true),
  ('Angello de Jesus', 'Argelia', 'Goldphoenixxx', 49049903, (select id from public.groups where code = 'J'), 'J1', true),
  ('Ary', 'Argentina', 'Flucamaleao', 26148093, (select id from public.groups where code = 'J'), 'J2', true),
  ('Augusto', 'Australia', 'Rodrigues Dostoievski FC', 21911314, (select id from public.groups where code = 'D'), 'D1', true),
  ('Braz', 'Austria', 'INSANOS22 FC', 21166384, (select id from public.groups where code = 'J'), 'J3', true),
  ('Brena Castro', 'Belgica', 'Sport Club Coquinha Geladaa', 21252257, (select id from public.groups where code = 'G'), 'G1', true),
  ('Bruno Pinheiro', 'Bosnia', 'Inazuma bk fc', 8947926, (select id from public.groups where code = 'B'), 'B1', true),
  ('Bruno Santos', 'Brasil', 'CR.bruvas.VG', 11885204, (select id from public.groups where code = 'C'), 'C1', true),
  ('BUENOy', 'Cabo Verde', 'King Bueno', 51093439, (select id from public.groups where code = 'H'), 'H2', true),
  ('Bussunda', 'Canada', 'Tabajara Team', 51316752, (select id from public.groups where code = 'B'), 'B2', true),
  ('CLECYO TADEU', 'Catar', 'CTFNFC', 1868920, (select id from public.groups where code = 'B'), 'B3', true),
  ('Daniel Alves', 'Colombia', 'FlaCaixa', 3804100, (select id from public.groups where code = 'K'), 'K1', true),
  ('Davi', 'Coreia do Sul', 'LOSS CLUB FC', 50937109, (select id from public.groups where code = 'A'), 'A2', true),
  ('Elcius Ferreira', 'Costa do Marfim', 'Flu Paraiba FC', 10348841, (select id from public.groups where code = 'E'), 'E2', true),
  ('Euller Seguros', 'Croacia', 'EULLER SEGUROS FC', 17893306, (select id from public.groups where code = 'L'), 'L1', true),
  ('Elvan Leao', 'Curacao', 'EL Engenharia', 3494253, (select id from public.groups where code = 'E'), 'E3', true),
  ('Flavio Leao', 'Egito', 'Verdao-Gpi', 25698150, (select id from public.groups where code = 'G'), 'G2', true),
  ('Flavio Leao', 'Equador', 'Camaleao do Sul FL', 280, (select id from public.groups where code = 'E'), 'E4', true),
  ('Gabriel', 'Escocia', 'MinhaEsposaDeixouFC', 51316876, (select id from public.groups where code = 'C'), 'C2', true),
  ('Hiago', 'Espanha', 'FC Loucura', 51335700, (select id from public.groups where code = 'H'), 'H3', true),
  ('Higor Silva', 'Estados Unidos', 'Inimigos Da Bola FC', 51335005, (select id from public.groups where code = 'D'), 'D2', true),
  ('Iago Valcacer', 'Franca', 'Valcacer CFC', 47712537, (select id from public.groups where code = 'I'), 'I1', true),
  ('Isaque Alencar', 'Gana', 'PikudosFC', 51319971, (select id from public.groups where code = 'L'), 'L2', true),
  ('Jairan Bandeira', 'Haiti', 'BandeirasFC', 25588062, (select id from public.groups where code = 'C'), 'C3', true),
  ('Joao Calixto', 'Holanda', 'MTAC_FUTEBOL_CLUBE', 11011243, (select id from public.groups where code = 'F'), 'F1', true),
  ('Jonas Aguiar', 'Inglaterra', 'Locomotiva SEP FC', 8533101, (select id from public.groups where code = 'L'), 'L3', true),
  ('Jorge Henrique', 'Ira', 'Spartanos GPI', 6498420, (select id from public.groups where code = 'G'), 'G3', true),
  ('Kaio Felipe', 'Iraque', '20te Comer FC', 18393254, (select id from public.groups where code = 'I'), 'I2', true),
  ('Kaio Felipe Reis', 'Japao', 'Bonde da Uncao', 51319936, (select id from public.groups where code = 'F'), 'F2', true),
  ('Kevynn Teixeira', 'Jordania', 'La Bestia Negra Esporte Club', 1420273, (select id from public.groups where code = 'J'), 'J4', true),
  ('Luiz Fernando', 'Marrocos', 'Karta city', 29523428, (select id from public.groups where code = 'C'), 'C4', true),
  ('Luiz Felipe', 'Mexico', 'Porco Milionario FC', 50988454, (select id from public.groups where code = 'A'), 'A3', true),
  ('Markus Vinicius', 'Noruega', 'Camisa Verde', 2171766, (select id from public.groups where code = 'I'), 'I3', true),
  ('Mateus Maximo', 'Nova Zelandia', 'MxSports Fc', 811729, (select id from public.groups where code = 'G'), 'G4', true),
  ('Matheus Rodrigues', 'Panama', 'EL Fenix F.C', 6046227, (select id from public.groups where code = 'L'), 'L4', true),
  ('Mikeyas Rodrigues', 'Paraguai', 'San Rodrigues Footbaal club', 7281771, (select id from public.groups where code = 'D'), 'D3', true),
  ('Mister Jesus', 'Portugal', 'Flamengo Libertadores2019', 25640313, (select id from public.groups where code = 'K'), 'K2', true),
  ('Pablo', 'RD Congo', 'F.C. BAYEN DE MADRID', 3187198, (select id from public.groups where code = 'K'), 'K3', true),
  ('Pablo Donizete', 'Republica Tcheca', 'Real Escalado FC', 402600, (select id from public.groups where code = 'A'), 'A4', true),
  ('Robson Aguiar', 'Senegal', 'AGROCAMPO 3312 4309 GPI', 9747076, (select id from public.groups where code = 'I'), 'I4', true),
  ('Rodolfo', 'Suecia', 'Rorintias', 51006662, (select id from public.groups where code = 'F'), 'F3', true),
  ('Savio Barbosa', 'Suica', 'Metodo Acustica', 44815445, (select id from public.groups where code = 'B'), 'B4', true),
  ('Savio Santos', 'Tunisia', 'Labregada FC', 202201, (select id from public.groups where code = 'F'), 'F4', true),
  ('Tayllon', 'Turquia', 'Pro Ghast', 49517627, (select id from public.groups where code = 'D'), 'D4', true),
  ('Vagner Alves', 'Uruguai', 'YMT10', 18808833, (select id from public.groups where code = 'H'), 'H4', true),
  ('Walter Luis', 'Uzbequistao', 'GurupiEC', 14831930, (select id from public.groups where code = 'K'), 'K4', true)
on conflict (cartola_team_id) do update
set display_name = excluded.display_name,
    represented_country = excluded.represented_country,
    cartola_team_name = excluded.cartola_team_name,
    group_id = excluded.group_id,
    seed_label = excluded.seed_label,
    is_active = excluded.is_active;
